title: "ObservaMigra"
description: "Blog sobre migração, discursos públicos e políticas comparadas"
theme: theme: jekyll-theme-minimal
# Navegação superior
nav:
  - title: "Início"
    url: "/"
  - title: "Sobre"
    url: "/sobre/"

